package com.atom.android.muvik.utils

object Constant {

    private const val PROJECT_NAME = "com.atom.android.muvik."
    const val EXTRA_LIST_SONG = PROJECT_NAME + "EXTRA_LIST_SONG"
    const val EXTRA_CURRENT_SONG = PROJECT_NAME + "EXTRA_CURRENT_SONG"
    const val EXTRA_POSITION_SONG = PROJECT_NAME + "EXTRA_POSITION_SONG"
    const val EXTRA_ACTION_FLAG = PROJECT_NAME + "EXTRA_ACTION_FLAG"
    const val EXTRA_START = PROJECT_NAME + "EXTRA_START"


    const val ACTION_PLAY = PROJECT_NAME + "PLAY"
    const val ACTION_PAUSE = PROJECT_NAME + "PAUSE"
    const val ACTION_RESUME = PROJECT_NAME + "RESUME"
    const val ACTION_NEXT = PROJECT_NAME + "NEXT"
    const val ACTION_PREVIOUS = PROJECT_NAME + "PREVIOUS"

    const val INTENT_FILTER_ACTION_SERVICE_TO_ACTIVITY_MUSIC =
        PROJECT_NAME + "INTENT_FILTER_ACTION_SERVICE_TO_ACTIVITY_MUSIC"
    const val INTENT_FILTER_ACTION_ACTIVITY_TO_SERVICE_MUSIC =
        PROJECT_NAME + "INTENT_FILTER_ACTION_ACTIVITY_TO_SERVICE__MUSIC"

    const val SHARED_PREF = PROJECT_NAME + "SHARED_PREF"
    const val SHARED_PREF_LOOP_SONG = PROJECT_NAME + "SHARED_PREF_LOOP_SONG"
    const val SHARED_PREF_MIX_SONG = PROJECT_NAME + "SHARED_PREF_MIX_SONG"
    const val SHARED_PREF_INPUT_FORMAT = PROJECT_NAME + "INPUT_FORMAT"
    const val SHARED_PREF_DARK_MODE = PROJECT_NAME + "DARK_MODE"
    const val SHARED_PREF_RESET_SETTING = PROJECT_NAME + "RESET_SETTING"

    const val SECOND_TO_MIL = 1000
    const val TIME_UPDATE_SEEK_BAR = 1000L
    const val TIME_START_UPDATE_TIME_SONG = 0L
    const val HOUR_TO_SECOND = 60
    const val DEGREE = 360

    var LOOP_SONG = false
    var MIX_SONG = false
    var INPUT_FORMAT = "MUSIC"
}
